disabled = false
languageCode = "pt-br"
languageName = "Português (Brasil)"
weight = 1
title = "Casa Comum"

[params]
displayName = "PT-BR"
isoCode = "pt-br"
rtl = false
dateFormat = "2 January 2006"
description = "Esposo e pai. Leigo na Igreja Anglicana no Brasil."
author = { name = "Rhuan Emanuel", image = "avatar.jpeg", headline = "Um blog comum sobre a tradição anglicana.", bio = "Esposo, Pai, Ministro Leigo.", links = [ { instagram = "https://instagram.com/rhnrod", threads = "https://www.threads.net/@rhnrod", mastodon = "https://mastodon.social/@rhnrod" } ] }
logo = "android-chrome-512x512.png"
